#!/bin/bash

USER_JENKINS=jenkins
GROUP_DOCKER=docker

function getDockerSocketGroup () {
	echo "$(ls -al /var/run/docker.sock | awk '{print $4}')"
}

# Display the containerbanner
cat /banner

# Change docker socket user
echo ''
echo "***** docker-socket *****"
echo "Current user: $(whoami)"
echo "/var/run/docker.sock is currently in group:" $(getDockerSocketGroup)
echo "Changing group of docker.sock to: $GROUP_DOCKER"
sudo chown :$GROUP_DOCKER /var/run/docker.sock
echo "/var/run/docker.sock is now in group:" $(getDockerSocketGroup)
echo "*************************"
echo ''

# Running jenkins
exec /sbin/tini -- /usr/local/bin/jenkins.sh
